CREATE TABLE PACJENT(
	ID_PACJENT SERIAL PRIMARY KEY,
	PESEL CHAR(11) UNIQUE,
	IMIE VARCHAR(50) NOT NULL,
	NAZWISKO VARCHAR(50) NOT NULL,
	DATA_URODZENIA DATE NOT NULL,
	PLEC VARCHAR(2) NOT NULL,
	TELEFON VARCHAR(10) NOT NULL
);

/*CREATE TABLE LEKARZ(
	ID_LEKARZ SERIAL PRIMARY KEY,
	IMIE VARCHAR(50) NOT NULL,
	NAZWISKO VARCHAR(50) NOT NULL,
	SPECJALIZACJA VARCHAR(50) NOT NULL
);*/

CREATE TABLE UZYTKOWNICY(
	ID_UZYTKOWNIKA SERIAL PRIMARY KEY ,
	LOGIN VARCHAR(50) UNIQUE,
	PASS VARCHAR(256) NOT NULL,
	IMIE VARCHAR(50) NOT NULL,
	NAZWISKO VARCHAR(50) NOT NULL,
	STANOWISKO VARCHAR(50) NOT NULL,
	LEKARZ INTEGER NOT NULL,
	ETYKIETA INTEGER NOT NULL
);

CREATE TABLE GABINET(
	ID_GABINET SERIAL PRIMARY KEY,
	NUMER integer UNIQUE ,
	WIELKOSC integer NOT NULL
);

CREATE TABLE WIZYTA(
	ID_WIZYTA SERIAL PRIMARY KEY,
	DATA_WIZYTY TIMESTAMP WITHOUT TIME ZONE NOT NULL,
	STATUS_WIZYTY VARCHAR(20) NOT NULL,
	LEKARZ INTEGER REFERENCES UZYTKOWNICY(ID_UZYTKOWNIKA),
	PACJENT INTEGER REFERENCES PACJENT(ID_PACJENT),
	GABINET INTEGER REFERENCES GABINET(ID_GABINET)
);

CREATE TABLE DIAGNOZA(
	ID_DIAGNOZA SERIAL PRIMARY KEY,
	OPIS VARCHAR(200) NOT NULL,
	WIZYTA INTEGER REFERENCES WIZYTA(ID_WIZYTA)
);

CREATE TABLE ETYKIETY(
	ID_ETYKIETY SERIAL PRIMARY KEY,
	TABELA VARCHAR(50) NOT NULL,
	ETYKIETA INTEGER NOT NULL
);

CREATE TABLE LEK(
	ID_LEK SERIAL PRIMARY KEY,
	NAZWA VARCHAR(50) UNIQUE,
	OPIS VARCHAR(200) NOT NULL
);

CREATE TABLE PRZEPISANE_LEKI(
	ID_DIAGNOZA INTEGER REFERENCES DIAGNOZA(ID_DIAGNOZA),
	ID_LEK INTEGER REFERENCES LEK(ID_LEK),
	PRIMARY KEY(ID_DIAGNOZA, ID_LEK)
);